# Generated by Django 3.2.25 on 2024-07-09 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('mood', models.CharField(choices=[('happy', '😊'), ('sad', '😢'), ('angry', '😡'), ('neutral', '😐')], max_length=10, verbose_name='감정')),
                ('weather', models.CharField(choices=[('sunny', '☀️'), ('rainy', '🌧️'), ('cloudy', '☁️'), ('snowy', '❄️')], max_length=10, verbose_name='날씨')),
                ('image', models.ImageField(blank=True, null=True, upload_to='diary_images/', verbose_name='이미지')),
                ('tags', models.CharField(blank=True, max_length=100, verbose_name='태그')),
                ('content', models.TextField(verbose_name='내용')),
            ],
        ),
    ]
