# Generated by Django 3.2.25 on 2024-07-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='제목'),
        ),
    ]
