# Generated by Django 3.2.25 on 2024-07-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_diaryentry_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaryentry',
            name='image',
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='diary_images/', verbose_name='이미지 1'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='diary_images/', verbose_name='이미지 2'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='diary_images/', verbose_name='이미지 3'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='diary_images/', verbose_name='이미지 4'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='diary_images/', verbose_name='이미지 5'),
        ),
    ]
