# Generated by Django 3.2.25 on 2024-07-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20240709_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='memo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='메모'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='mood',
            field=models.CharField(choices=[('happy', '😊'), ('sad', '😢'), ('angry', '😠'), ('neutral', '😐')], max_length=10, verbose_name='감정'),
        ),
    ]
